datasetPath = "/storage/mstrobl/dataset"
waveformPath = "/storage/mstrobl/waveforms"
featurePath = "/storage/mstrobl/features/"
quantumPath = "/storage/mstrobl/quantum/"
modelsPath = "/storage/mstrobl/models"

testDatasetPath = "/storage/mstrobl/testDataset"
testWaveformPath = "/storage/mstrobl/testWaveforms"
testFeaturePath = "/storage/mstrobl/testFeatures"
testQuantumPath = "/storage/mstrobl/testDataQuantum"